version: "3"

services: 

  tomcat: 
    image: amarnath510/docker-my-tomcat-image
    container_name: tomcat-docker-compose
    ports: 
      - 8181:8080

  mysql: 
    image: amarnath510/mysql-5.6-docker-image
    container_name: mysql-docker-compose
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: company

